---
name: my-bloody-jenkins
version: 0.1.6
appVersion: "v2.138.1-76"
description: >
   A Helm chart for my-bloody-jenkins - a self configured jenkins docker image, based on Jenkins LTS.
   Inspired by https://github.com/kubernetes/charts/tree/master/stable/jenkins, but better suites https://github.com/odavid/my-bloody-jenkins.
sources:
  - https://github.com/odavid/my-bloody-jenkins
  - https://github.com/odavid/my-bloody-jenkins-helm-chart
  - https://github.com/odavid/jenkins-jnlp-slave
maintainers:
  - name: odavid
    email: ohad.david@gmail.com
