apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "my-bloody-jenkins.fullname" . }}
  labels:
    app: {{ template "my-bloody-jenkins.name" . }}
    chart: {{ template "my-bloody-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jenkins-config.yml: |-
{{- if .Values.managedConfig }}
{{ toYaml .Values.managedConfig | indent 4 }}
{{- end }}

  k8s-default-cloud.yml: |-
{{- if and (.Values.defaultK8sCloud) (.Values.defaultK8sCloud.enabled) }}
    clouds:
      {{ .Values.defaultK8sCloud.name | default "k8s" }}:
        type: kubernetes
        jenkinsUrl: http://{{ include "my-bloody-jenkins.fullname" . }}:8080
        namespace: {{ .Release.Namespace }}
        templates:
          - name: kubeslave
            image: {{ .Values.defaultK8sCloud.slaveImage | default "odavid/jenkins-jnlp-slave:latest" }}
            labels:
{{ toYaml (default .Values.defaultK8sCloud.labels) | indent 14 }}
            remoteFs: {{ .Values.defaultK8sCloud.remoteFs | default "/home/jenkins" }}
            jvmArgs: {{ .Values.defaultK8sCloud.jvmArgs | default "-Xmx1g" }}
            volumes:
              - '/var/run/docker.sock:/var/run/docker.sock'
{{- end }}
