{{- with .Values.ingress.tls }}
{{- if and .privateKey .certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "my-bloody-jenkins.tlsSecretName" $ }}
  labels:
    app: {{ template "my-bloody-jenkins.name" $ }}
    chart: {{ template "my-bloody-jenkins.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .privateKey | b64enc }}
{{- end }}
{{- end }}
